
TRAIN:
  ENABLE: False
  DATASET: Ucf
  BATCH_SIZE: 1
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: slowfast/I3D_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2
  CHECKPOINT_EPOCH_RESET: True

TENSORBOARD:
  ENABLE: True
  CLASS_NAMES_PATH: /media/cats/32b7c353-4595-42d8-81aa-d029f1556567/ucf/Ucf-labels.json
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: False # Set to True to visualize model weights.
    ACTIVATIONS: False # Set to True to visualize feature maps.
    INPUT_VIDEO: False # Set to True to visualize the input video(s) for the corresponding feature maps.
    LAYER_LIST: ['s5/pathway0_res2'] # List of layer names to visualize weights and activations for.
    GRAD_CAM:
      ENABLE: True
      LAYER_LIST: ['s5/pathway0_res2'] # List of CNN layers to use for Grad-CAM visualization method.
                  # The number of layer must be equal to the number of pathway(s).
      USE_TRUE_LABEL: True
DATA:
  PATH_TO_DATA_DIR: /media/cats/32b7c353-4595-42d8-81aa-d029f1556567/ucf
  NUM_FRAMES: 64
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  RANDOM_FLIP: False

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.3
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 14, 18]
  # MAX_EPOCH: 22
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 0.19
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 10
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  # DETACH_FINAL_FC: True
TEST:
  ENABLE: False
  DATASET: ucf
  BATCH_SIZE: 1
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
LOG_MODEL_INFO: False
