TRAIN:
  ENABLE: True
  DATASET: SyntheticMotion
  BATCH_SIZE: 10
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME_FROM_CHECKPOINT: True
  # If no checkpoint file is specified, it will resume from the latest epoch checkpoint 
  CHECKPOINT_FILE_PATH: /research/cwloka/data/action_attn/synthetic_motion_7_classes/I3D_8x8_R50.pkl
  CHECKPOINT_TYPE: caffe2

TENSORBOARD:
  ENABLE: False
  CLASS_NAMES_PATH: /research/cwloka/data/action_attn/synthetic_motion_7_classes/ispy_0.1_9/synthetic_motion_labels.json
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: False # Set to True to visualize model weights.
    ACTIVATIONS: False # Set to True to visualize feature maps.
    INPUT_VIDEO: False # Set to True to visualize the input video(s) for the corresponding feature maps.
    GRAD_CAM:
      ENABLE: True
      LAYER_LIST: ['s5/pathway0_res2'] # List of CNN layers to use for Grad-CAM visualization method.
                  # The number of layer must be equal to the number of pathway(s).
      USE_TRUE_LABEL: False
      METHOD: grad_cam

DATA:
  PATH_TO_DATA_DIR: /research/cwloka/data/action_attn/synthetic_motion_7_classes/ispy_0.1_9
  NUM_FRAMES: 32
  # SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  # INPUT_CHANNEL_NUM: [3, 3]

RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]

NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax

#   NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
#   SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
#   SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]

# NONLOCAL:
#   LOCATION: [[[], []], [[], []], [[], []], [[], []]]
#   GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
#   INSTANTIATION: dot_product

BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200

SOLVER:
  BASE_LR: 0.0001
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 40, 60]
  # MAX_EPOCH: 22
  MAX_EPOCH: 92
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  WARMUP_EPOCHS: 0.19
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd

# SOLVER:
#   BASE_LR: 0.1
#   LR_POLICY: cosine
#   MAX_EPOCH: 100
#   MOMENTUM: 0.9
#   WEIGHT_DECAY: 1e-4
#   WARMUP_EPOCHS: 34.0
#   WARMUP_START_LR: 0.01
#   OPTIMIZING_METHOD: sgd

MODEL:
  NUM_CLASSES: 7
  ARCH: i3d
  MODEL_NAME: ResNet
  # ARCH: slowfast
  # MODEL_NAME: SlowFast
  DROPOUT_RATE: 0.5
  
TEST:
  ENABLE: False
  DATASET: SyntheticMotion
  BATCH_SIZE: 2
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
  INSPECT:
    SAVE_SEQ_COUNT: 30
    SAVE_FRAMES: True
    SAVE_VIDEO: False
    SHUFFLE: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /research/cwloka/data/action_attn/synthetic_motion_7_classes/i3d_outputs
